// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFt9v_-pgLuLVg8w_CdLSpmGSAV_6hT64',
    appId: '1:95420155329:web:19f3fcc52d5a9781d4db40',
    messagingSenderId: '95420155329',
    projectId: 'reservation-24f23',
    authDomain: 'reservation-24f23.firebaseapp.com',
    storageBucket: 'reservation-24f23.firebasestorage.app',
    measurementId: 'G-YZSPWZB3DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzKjutYK8wewHu4fqzQuFkzH4W02lkxCg',
    appId: '1:95420155329:android:ea7b97c3ff000319d4db40',
    messagingSenderId: '95420155329',
    projectId: 'reservation-24f23',
    storageBucket: 'reservation-24f23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGm_5OsVNvpEXOFbTveyXFx_4a0llUElQ',
    appId: '1:95420155329:ios:b56a03f04276d5bad4db40',
    messagingSenderId: '95420155329',
    projectId: 'reservation-24f23',
    storageBucket: 'reservation-24f23.firebasestorage.app',
    iosBundleId: 'com.example.ticketin',
  );
}
