// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIBKFFgd7_PysHz4ap7tbEX_krJ8CkRPU',
    appId: '1:643538405051:web:773e00dfeede6aafb04b9e',
    messagingSenderId: '643538405051',
    projectId: 'ticektin',
    authDomain: 'ticektin.firebaseapp.com',
    storageBucket: 'ticektin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCjXQ5B5F6sS62BCMMWKUJGW5zcCnsx1Q',
    appId: '1:643538405051:android:a5d2e9684383fa5fb04b9e',
    messagingSenderId: '643538405051',
    projectId: 'ticektin',
    storageBucket: 'ticektin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6s6ikrQBoZXtgJFIgdJ9FqU9eAPYu2oY',
    appId: '1:643538405051:ios:c3dbf7a340372e0db04b9e',
    messagingSenderId: '643538405051',
    projectId: 'ticektin',
    storageBucket: 'ticektin.firebasestorage.app',
    iosBundleId: 'com.example.ticketin',
  );

}